# Generated by Django 5.0.2 on 2024-10-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register",
            old_name="firs_name",
            new_name="first_name",
        ),
    ]
