# Generated by Django 5.0.2 on 2024-10-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_rename_firs_name_register_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="first_name",
        ),
        migrations.AddField(
            model_name="register",
            name="username",
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
