# Generated by Django 5.0.2 on 2024-10-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_register_first_name_register_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="username",
        ),
        migrations.AddField(
            model_name="register",
            name="first_name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
